var config = {
    USER_SUCCESSFULLY_CREATE: 'user create',
    USER_NOT_FOUND: 'no user found',
    WRONG_PASSWORD: 'incorrect password',
    USER_LOGGED_SUCCESSFULLY: 'user logged',
    SKILL_ADD: 'skill add successfully',
    UPDATE_SKILL: 'update skill',
    FIND_SKILL: 'find skills',
    SKILL_NOT_FOUND: 'skill not found',
    SKILL_FOUND: 'skill found',
    NO_SKILL: 'not skill found',
    DELETE_SKILL: 'delete skill successfully',
    NO_USER_FOUND: 'no user',
    USER_FOUND: 'user found',
    NO_USER: 'user not found',
    FOUND_USER: 'user found',
    USER_SKILL_NOT_FOUND: ' no user skill',
    USER_SKILL_FOUND: 'user skill found',
    EXPERIENCE_NOT_FOUND: 'no experience',
    EXPERIENCE_FOUND: 'experience found',
    UPDATE_EXPERIENCE: 'update experience',
    EDUCATION_NOT_FOUND: 'no education',
    EDUCATION_FOUND: 'education found',
    UPDATE_EDUCATION: 'update education',
    DATA_RETRIVED_SUCCESSFULLY: 'data retrived successfully',
    N0_POST: 'no post found',
    POST_FIND: 'find posts',
    NO_JOB: 'no jobs',
    JOB_FIND: 'find job successfully',
    GET_DATA:'get data successfully',


}
module.exports = config