var constant = {
    USER_CREATE_SUCCESSFULLY: 'user create',
    USER_NOT_FOUND: 'no user ',
    WRONG_PASSWORD: 'wrong password',
    USER_LOGGED_SUCCESSFULLY: 'login successfully',
    USER_SKILL_CREATE: 'skill create',
    SKILLS_ADD: 'skills add',
    USER_UPDATE: 'user update',
    CREATE_EDUCATION_SYSTEM: 'create education',
    NO_USER_FOUND: 'user not found',
    FIND_EDUCATION: 'find education',
    UPDATE_EDUCATION: 'update education successfully',
    NOT_USER: 'no user found',
    DELETE_USER_SUCCESSFULLY: 'delete user',
    EXPERIENCE_CREATE: 'create experience',
    USER_NO: 'no user',
    EXPERIENCE_FIND: 'experience find',
    UPDATE_EXPERIENCE: 'update experience',
    USER_DELETE_SUCCESSFULLY: 'delete successfully',
    DATA_RETRIVED_SUCCESSFULLY: 'data retrived',
    ADD_POST: 'add post',
    USER_NOT_GET: 'no user found',
    POST_FIND: 'posts find',
    ADDPOST_UPDATE: 'addpost update successfully',
    DELETE_POST: 'delete post',
    ADD_JOB_FIELD_SUCCESSFULLY: 'add job',
    USER_NOT_EXISTS: 'no user',
    ADD_JOBS: 'add job successfully',
    UPDATE_JOB: 'update jobs',
    DELETE_JOB: 'delete job',
    NO_USER: 'user not found',
    FOUND_NO_USER: 'no user'
}
module.exports = constant